spring:
  application:
    name: Goto
  batch:
    job:
      enabled: false
  cloud:
    aws:
      region:
        static: ap-northeast-2
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: "!test"
    import: 'optional:aws-parameterstore:/goto/'

security:
  jwt:
    issuer: GOTO-BE
    access-token-ttl: 60m
    refresh-token-ttl: 14d

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

tour-api:
  base-url: "http://apis.data.go.kr/B551011/KorWithService2"
  service-key: ${TOUR_API_SERVICE_KEY}
  mobile-os: "ETC"
  mobile-app: "Goto"
