spring:
  application:
    name: Goto
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never
  cloud:
    aws:
      region:
        static: ap-northeast-2
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: "!test"
    import: 'optional:aws-parameterstore:/goto/'

security:
  jwt:
    issuer: GOTO-BE
    access-token-ttl: 60m
    refresh-token-ttl: 14d

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

tour-api:
  base-url: "http://apis.data.go.kr/B551011/KorWithService2"
  mobile-os: "ETC"
  mobile-app: "Goto"
  detail-quota: 250
  detail-concurrency: 1
  detail-queue-capacity: 250
  detail-await-termination-seconds: 60

goto:
  batch:
    initial-load:
      auto-run-enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
